table job_postings_fact
	lineageTag: 7c511353-702a-4c91-bd9a-e4a3ab8bef44

	column job_id
		dataType: int64
		formatString: 0
		lineageTag: 8d488e53-5d32-419c-9b02-ca980ca8f364
		summarizeBy: none
		sourceColumn: job_id

		annotation SummarizationSetBy = Automatic

	column company_id
		dataType: int64
		formatString: 0
		lineageTag: 5e57669d-e9fb-4d4e-baa5-92173e41c817
		summarizeBy: none
		sourceColumn: company_id

		annotation SummarizationSetBy = Automatic

	column job_title_short
		dataType: string
		lineageTag: 64fdffdc-a03c-466c-a169-358131aeec0a
		summarizeBy: none
		sourceColumn: job_title_short

		annotation SummarizationSetBy = Automatic

	column job_title
		dataType: string
		lineageTag: 8069feb3-ed61-44c8-99ac-0fda37294af7
		summarizeBy: none
		sourceColumn: job_title

		annotation SummarizationSetBy = Automatic

	column job_location
		dataType: string
		lineageTag: ff94232c-4c60-4ac1-bee3-97439c240aa2
		summarizeBy: none
		sourceColumn: job_location

		annotation SummarizationSetBy = Automatic

	column job_via
		dataType: string
		lineageTag: d4af98ac-06cd-4a97-b870-18c0ace4ae76
		summarizeBy: none
		sourceColumn: job_via

		annotation SummarizationSetBy = Automatic

	column job_schedule_type
		dataType: string
		lineageTag: 7045ad08-8e53-42b5-8288-a043def4c936
		summarizeBy: none
		sourceColumn: job_schedule_type

		annotation SummarizationSetBy = Automatic

	column job_work_from_home
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b2ec6106-90b0-45f5-a707-f68b011d544c
		summarizeBy: none
		sourceColumn: job_work_from_home

		annotation SummarizationSetBy = Automatic

	column search_location
		dataType: string
		lineageTag: fe74e3cd-ace9-40a3-b425-f96251a6f8ba
		summarizeBy: none
		sourceColumn: search_location

		annotation SummarizationSetBy = Automatic

	column job_posted_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8c60a8d1-9b6a-411b-b2d1-6d609af16fd7
		summarizeBy: none
		sourceColumn: job_posted_date

		variation Variation
			isDefault
			relationship: d985e6e9-6c6d-462e-899f-584763acdbc1
			defaultHierarchy: LocalDateTable_b42a1beb-43d7-4f16-8830-86e2a16f21fa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column job_no_degree_mention
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a4dc4146-6855-4c61-923d-d98eb6c4c4c1
		summarizeBy: none
		sourceColumn: job_no_degree_mention

		annotation SummarizationSetBy = Automatic

	column job_health_insurance
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: dd7103a4-84d6-4f9e-aa00-08dc3e0aeac0
		summarizeBy: none
		sourceColumn: job_health_insurance

		annotation SummarizationSetBy = Automatic

	column job_country
		dataType: string
		lineageTag: 2a53364d-7a42-48d2-8d65-919b52bef64a
		summarizeBy: none
		sourceColumn: job_country

		annotation SummarizationSetBy = Automatic

	column salary_rate
		dataType: string
		lineageTag: d5bd3d7d-a3a4-4436-aa07-387f351652ab
		summarizeBy: none
		sourceColumn: salary_rate

		annotation SummarizationSetBy = Automatic

	column salary_year_avg
		dataType: int64
		formatString: 0
		lineageTag: b44ecdc9-b4d5-445e-85d0-12672e72b29b
		summarizeBy: sum
		sourceColumn: salary_year_avg

		annotation SummarizationSetBy = Automatic

	column salary_hour_avg
		dataType: int64
		formatString: 0
		lineageTag: 83b93433-0a69-4ed4-bcc7-fb6462854b1d
		summarizeBy: sum
		sourceColumn: salary_hour_avg

		annotation SummarizationSetBy = Automatic

	column 'Seniority Level'
		dataType: string
		lineageTag: 1aa85395-5b36-445c-8e0f-5aee8f7b6d28
		summarizeBy: none
		sourceColumn: Seniority Level
		sortByColumn: 'Seniority Rank'

	column 'Seniority Rank'
		dataType: int64
		isHidden
		lineageTag: 46f4b8cf-a273-47f0-a7f5-db67bb5b515f
		summarizeBy: none
		sourceColumn: Seniority Rank

	column 'Job Platform'
		dataType: string
		lineageTag: 7a6d83db-ded4-4209-9151-53e2d0f03458
		summarizeBy: none
		sourceColumn: Job Platform

	column 'Remote Status'
		dataType: string
		lineageTag: 66d7606f-9be7-491c-b72d-5148f7df7e0b
		summarizeBy: none
		sourceColumn: Remote Status

	column 'Degree Requirement'
		dataType: string
		lineageTag: 1f1f227f-1080-4612-a4dc-6a6645aa23a3
		summarizeBy: none
		sourceColumn: Degree Requirement

	column Insurance
		dataType: string
		lineageTag: f9c5f504-1488-452a-b61a-6d2d7a9a9906
		summarizeBy: none
		sourceColumn: Insurance

	/// Acronym role labels for the tile slicer and compact axes (DA/BA/DE/DS/SE + senior/ML/cloud codes)
	column 'Role Code' = SWITCH(job_postings_fact[job_title_short], "Data Analyst", "DA", "Business Analyst", "BA", "Data Engineer", "DE", "Data Scientist", "DS", "Software Engineer", "SE", "Senior Data Analyst", "Sr DA", "Senior Data Engineer", "Sr DE", "Senior Data Scientist", "Sr DS", "Machine Learning Engineer", "MLE", "Cloud Engineer", "CE", job_postings_fact[job_title_short])
		dataType: string
		lineageTag: 3e1a9c7b-5d20-48f6-9b41-c8a2e07d5f13
		summarizeBy: none
		sortByColumn: 'Role Sort'

	column 'Role Sort' = SWITCH(job_postings_fact[job_title_short], "Data Analyst", 1, "Business Analyst", 2, "Data Engineer", 3, "Data Scientist", 4, "Software Engineer", 5, "Senior Data Analyst", 6, "Senior Data Engineer", 7, "Senior Data Scientist", 8, "Machine Learning Engineer", 9, "Cloud Engineer", 10, 11)
		dataType: int64
		isHidden
		lineageTag: 8f4b2d6e-1a37-4c95-b208-7e5c3a90d461
		summarizeBy: none

	partition job_postings_fact = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ADMIN\Desktop\SQL_Data_engineering_projects\Project\portfolio\portfolio\powerbi\p1\project1_data\job_postings_fact.csv"),[Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"job_id", Int64.Type}, {"company_id", Int64.Type}, {"job_title_short", type text}, {"job_title", type text}, {"job_location", type text}, {"job_via", type text}, {"job_schedule_type", type text}, {"job_work_from_home", type logical}, {"search_location", type text}, {"job_posted_date", type datetime}, {"job_no_degree_mention", type logical}, {"job_health_insurance", type logical}, {"job_country", type text}, {"salary_rate", type text}, {"salary_year_avg", type number}, {"salary_hour_avg", type number}}),
				    #"Added Seniority" = Table.AddColumn(#"Changed Type", "Seniority Level", each
				        let t = Text.Lower([job_title] ?? "") in
				        if Text.Contains(t,"senior") or Text.Contains(t,"sr.") or Text.Contains(t,"sr ") or Text.Contains(t,"staff") or Text.Contains(t,"principal") or Text.Contains(t,"lead") then "senior"
				        else if Text.Contains(t,"junior") or Text.Contains(t,"jr.") or Text.Contains(t,"jr ") or Text.Contains(t,"entry") or Text.Contains(t,"intern") or Text.Contains(t,"graduate") or Text.Contains(t,"trainee") then "junior"
				        else "mid", type text),
				    #"Added Rank" = Table.AddColumn(#"Added Seniority", "Seniority Rank", each
				        if [Seniority Level] = "junior" then 1 else if [Seniority Level] = "mid" then 2 else 3, Int64.Type),
				    #"Added Platform" = Table.AddColumn(#"Added Rank", "Job Platform", each
				        let v = [job_via] ?? "" in if Text.StartsWith(v, "via ") then Text.Range(v, 4) else v, type text),
				    #"Added Remote" = Table.AddColumn(#"Added Platform", "Remote Status", each
				        if [job_work_from_home] = true then "Remote" else "On-site", type text),
				    #"Added Degree" = Table.AddColumn(#"Added Remote", "Degree Requirement", each
				        if [job_no_degree_mention] = true then "No degree mention" else "Degree mentioned", type text),
				    #"Added Insurance" = Table.AddColumn(#"Added Degree", "Insurance", each
				        if [job_health_insurance] = true then "Insurance" else "No insurance", type text)
				in
				    #"Added Insurance"

	annotation PBI_ResultType = Table

